// This file is intended as a way to add custom types for specific methods beyond the autogenerated method types
// It is meant to be additive to the SlackClient type
import { TypedAppsMethodTypes } from "./apps.ts";

export type TypedSlackAPIMethodsType = TypedAppsMethodTypes;
