/**
 * This file is intended as a way to add custom types for specific methods beyond the autogenerated method types
 * It is meant to be additive to the SlackClient type
 */
import { TypedAppsMethodTypes } from "./apps.ts";
import { TypedChatMethodTypes } from "./chat.ts";
import { TypedFunctionMethodTypes } from "./functions.ts";
import { TypedWorkflowsMethodTypes } from "./workflows/mod.ts";

/**
 * When adding a new type here, run `scripts/src/generate`
 * to remove any methods that may have gotten entered by that script
 */
export const methodsWithCustomTypes = [
  "apps.datastore.delete",
  "apps.datastore.bulkDelete",
  "apps.datastore.get",
  "apps.datastore.bulkGet",
  "apps.datastore.put",
  "apps.datastore.bulkPut",
  "apps.datastore.update",
  "apps.datastore.query",
  "apps.datastore.count",
  "apps.auth.external.get",
  "apps.auth.external.delete",
  "chat.postMessage",
  "functions.completeSuccess",
  "functions.completeError",
  "workflows.triggers.create",
  "workflows.triggers.list",
  "workflows.triggers.update",
  "workflows.triggers.delete",
];

export type TypedSlackAPIMethodsType =
  & TypedAppsMethodTypes
  & TypedChatMethodTypes
  & TypedFunctionMethodTypes
  & TypedWorkflowsMethodTypes;
