export const TriggerEventTypes = {
  ChannelCreated: "slack#/events/channel_created",
  DndUpdated: "slack#/events/dnd_updated",
  ReactionAdded: "slack#/events/reaction_added",
  UserJoinedChannel: "slack#/events/user_joined_channel",
  UserJoinedTeam: "slack#/events/user_joined_team",
  MessagePosted: "slack#/events/message_posted",
  MessageMetadataPosted: "slack#/events/message_metadata_posted",
  AppMention: "slack#/events/app_mention",
  ChannelArchive: "slack#/events/channel_archive",
  ChannelDeleted: "slack#/events/channel_deleted",
  ChannelRename: "slack#/events/channel_rename",
  ChannelShared: "slack#/events/channel_shared",
  ChannelUnarchive: "slack#/events/channel_unarchive",
  ChannelUnshared: "slack#/events/channel_unshared",
  EmojiChanged: "slack#/events/emoji_changed",
  MemberLeftChannel: "slack#/events/member_left_channel",
  PinAdded: "slack#/events/pin_added",
  PinRemoved: "slack#/events/pin_removed",
  ReactionRemoved: "slack#/events/reaction_removed",
  SharedChannelInviteAccepted: "slack#/events/shared_channel_invite_accepted",
  SharedChannelInviteApproved: "slack#/events/shared_channel_invite_approved",
  SharedChannelInviteDeclined: "slack#/events/shared_channel_invite_declined",
  SharedChannelInviteReceived: "slack#/events/shared_channel_invite_received",
} as const;
