import { type AdminAPIType } from "./admin.ts";
import { type ApiAPIType } from "./api.ts";
import { type AppsAPIType } from "./apps.ts";
import { type AuthAPIType } from "./auth.ts";
import { type BookmarksAPIType } from "./bookmarks.ts";
import { type BotsAPIType } from "./bots.ts";
import { type CallsAPIType } from "./calls.ts";
import { type ChannelsAPIType } from "./channels.ts";
import { type ChatAPIType } from "./chat.ts";
import { type ConversationsAPIType } from "./conversations.ts";
import { type DialogAPIType } from "./dialog.ts";
import { type DndAPIType } from "./dnd.ts";
import { type EmojiAPIType } from "./emoji.ts";
import { type EnterpriseAPIType } from "./enterprise.ts";
import { type FilesAPIType } from "./files.ts";
import { type FunctionsAPIType } from "./functions.ts";
import { type GroupsAPIType } from "./groups.ts";
import { type ImAPIType } from "./im.ts";
import { type MigrationAPIType } from "./migration.ts";
import { type MpimAPIType } from "./mpim.ts";
import { type OauthAPIType } from "./oauth.ts";
import { type OpenidAPIType } from "./openid.ts";
import { type PinsAPIType } from "./pins.ts";
import { type ReactionsAPIType } from "./reactions.ts";
import { type RemindersAPIType } from "./reminders.ts";
import { type RtmAPIType } from "./rtm.ts";
import { type SearchAPIType } from "./search.ts";
import { type StarsAPIType } from "./stars.ts";
import { type TeamAPIType } from "./team.ts";
import { type ToolingAPIType } from "./tooling.ts";
import { type UsergroupsAPIType } from "./usergroups.ts";
import { type UsersAPIType } from "./users.ts";
import { type ViewsAPIType } from "./views.ts";
import { type WorkflowsAPIType } from "./workflows.ts";

export type SlackAPIMethodsType = {
  admin: AdminAPIType;
  api: ApiAPIType;
  apps: AppsAPIType;
  auth: AuthAPIType;
  bookmarks: BookmarksAPIType;
  bots: BotsAPIType;
  calls: CallsAPIType;
  channels: ChannelsAPIType;
  chat: ChatAPIType;
  conversations: ConversationsAPIType;
  dialog: DialogAPIType;
  dnd: DndAPIType;
  emoji: EmojiAPIType;
  enterprise: EnterpriseAPIType;
  files: FilesAPIType;
  functions: FunctionsAPIType;
  groups: GroupsAPIType;
  im: ImAPIType;
  migration: MigrationAPIType;
  mpim: MpimAPIType;
  oauth: OauthAPIType;
  openid: OpenidAPIType;
  pins: PinsAPIType;
  reactions: ReactionsAPIType;
  reminders: RemindersAPIType;
  rtm: RtmAPIType;
  search: SearchAPIType;
  stars: StarsAPIType;
  team: TeamAPIType;
  tooling: ToolingAPIType;
  usergroups: UsergroupsAPIType;
  users: UsersAPIType;
  views: ViewsAPIType;
  workflows: WorkflowsAPIType;
};
