#!/bin/bash

# Writes the Function files based on a functions.json file existing alongside this script
deno run --allow-read --allow-net --allow-write ./scripts/src/generate.ts
echo "Formatting Slack function files..."
deno fmt --quiet ./src/generated/**/*.ts
echo "Linting Slack function files..."
deno lint --quiet ./src/generated/**/*.ts
