name: Deno Format, Lint and Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we test on both most recent stable version of deno (v1.x) as well as
        # the version of deno used by Run on Slack (as noted in https://api.slack.com/slackcli/metadata.json)
        deno-version:
          - v1.x
          - v1.46.2
          - v2.x
    permissions:
      contents: read
    steps:
      - name: Setup repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Run formatter, linter and tests
        run: deno task test
      - name: Generate CodeCov-friendly coverage report
        run: deno task generate-lcov
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        if: matrix.deno-version == 'v2.x'
        with:
          files: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  health-score:
    needs: test
    permissions:
      checks: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Report health score
        uses: slackapi/slack-health-score@d58a419f15cdaff97e9aa7f09f95772830ab66f7 # v0.1.1
        with:
          codecov_token: ${{ secrets.FILS_CODECOV_API_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          extension: ts
          include: src
