name: Deno

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deno:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run formatter, linter and tests
        run: deno task test

      - name: Generate CodeCov-friendly coverage report
        run: deno task generate-lcov

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v4
        with:
          file: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Report health score
        uses: slackapi/slack-health-score@v0
        with:
          codecov_token: ${{ secrets.FILS_CODECOV_API_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          extension: ts
          include: src
