# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run formatter, linter and tests
        run: deno task test

      - name: Generate CodeCov-friendly coverage report
        run: deno task coverage --lcov --output=codecov.lcov

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./codecov.lcov
