name: Deno Format, Lint and Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we test on both most recent stable version of deno (v1.x) as well as
        # the version of deno used by Run on Slack (as noted in https://api.slack.com/slackcli/metadata.json)
        deno-version: [v1.x, v1.45.4]
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Run formatter, linter and tests
        run: deno task test
      - name: Generate CodeCov-friendly coverage report
        run: deno task generate-lcov
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v4
        with:
          file: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  health-score:
    needs: test
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Report health score
        uses: slackapi/slack-health-score@v0
        with:
          codecov_token: ${{ secrets.FILS_CODECOV_API_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          extension: ts
          include: src
